### ISSUE TITLE
Cannot hide some apps

### ISSUE THREAD

**Issue by ash-sykes** [albu-razvan/Stario#16]
**Describe the bug**
Unable to hide a selection of apps

**To Reproduce**
Steps to reproduce:
1. No idea. See video

**Expected behaviour**
Can hide app

**Screenshots**

https://github.com/user-attachments/assets/b48a4abe-e572-4f58-bbd9-bd31efa5da75

**Smartphone (please complete the following information):**
 - Device: ZFold 5
 - OS: Android
 - Version 14

**Additional context**
Na

**Comment by albu-razvan** [comment]
@ash-sykes could you please check the [latest release](https://github.com/albu-razvan/Stario/releases/tag/v2.4) and report if the issue still persists?

**Comment by ash-sykes** [comment]
Have just checked the latest version and it unfortunately exhibits the same behaviour. Any app above a certain point can be hidden, any below it cannot be toggled

**Comment by albu-razvan** [comment]
Cannot replicate the behavior on ZFold 6, ZFold 5 (through Samsung Remote Test Lab) or the Android Emulator (folded). If you manage to replicate this on other devices, find a potential cause or identified a potential fix, please reply. This issue will be closed in the meantime.
