### ISSUE TITLE
Restarting the launcher doesn't work as expected

### ISSUE THREAD

**Issue by ash-sykes** [albu-razvan/Stario#19]
**Describe the bug**
Restarting the launcher causes a black screen to appear, that once dismissed, causes the homescreen pill to appear behind the app drawer search box

**To Reproduce**
Steps to reproduce:
1. Click on restart launcher from the app settings menu

**Expected behaviour**
App is restarted

**Screenshots**
![Screenshot_20240808_091011_Stario](https://github.com/user-attachments/assets/40a85a48-ac29-476a-a392-a55c9cae39cd)
![Screenshot_20240808_091039_Stario](https://github.com/user-attachments/assets/902ac85b-225f-4a62-a764-60b942999097)

**Smartphone (please complete the following information):**
 - Device: ZFold 5
 - OS: Android
 - Version 14

**Additional context**

**Comment by Myrstad** [comment]
I can attest to that restarting the launcher in version 2.3 removes the background, and causes a solid color background.

* Device: Pixel 6
* OS: Android 14
* Version: August Patch
