### ISSUE TITLE
v2.4 - App crashes on scrolling in the app drawer

### ISSUE THREAD

**Issue by SethPDA** [albu-razvan/Stario#36]
**Describe the bug**
App crashes on scrolling in the app drawer

**To Reproduce**
Steps to reproduce:
1. Start the launcher
2. Swipe up to open the app drawer
3. Wait for it to crash.

**Expected behaviour**
It shouldn't crash.

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 1
 - OS: Android 14

**Comment by Myrstad** [comment]
Same bug here.

Device: Pixel 6
OS: Android 14
