### ISSUE TITLE
Crash when open games category 

### ISSUE THREAD

**Issue by airon-main** [albu-razvan/Stario#43]
**Describe the bug**
As the title describes

**To Reproduce**
Steps to reproduce:
1. Go to 'categories'
2. Click on 'games category'
3. Crashes

**Expected behaviour**
Opens

**Screenshots**
All my games:
![Screenshot_2024-10-04-17-03-14-919_com.miui.home.jpg](https://github.com/user-attachments/assets/00fad25a-4ca6-44e3-8f91-c58311ab835b)
Recording:
https://github.com/user-attachments/assets/272b947c-ba35-423e-9caf-a8d9454df32f

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11T pro
 - OS: MIUI 14, Android 13
 - Version: Alpha 2.4

**Comment by albu-razvan** [comment]
Please reopen this issue if it still persists in the next release.
