### ISSUE TITLE
Widget bug

### ISSUE THREAD

**Issue by 1dhruvsingh** [albu-razvan/Stario#46]
So there is no option to remove a widget but soon enough i realized that If i drag already made widget to the bottom and hold it creates a glitch where you no longer can see the widget and nor you can scroll up to see the widget above ,and the widgets take up a lot of space ,like if I select medium even then it will occupy the space of a large widget obviously leaving the corners empty making it look like a UI glitch 

Phone - Oneplus nord CE 2 Lite 

Even though I am very new app development ,i would be very glad to be able to help

**Comment by 1dhruvsingh** [comment]
I can provide with an example from my other phone if you want

**Comment by albu-razvan** [comment]
> I can provide a video example

Please do

**Comment by 1dhruvsingh** [comment]
Issue 1: once you add a widget to the top you are not able to more ,it sometimes scrolls on itself to downwards or sometimes upward  

Issue 2: widget overlapping 

Issue 3: widget acts like a floating window and instead creates a gap where it should be

Will have to compress the video(it will reduce the quality), instead I will send via discord

**Comment by albu-razvan** [comment]
Related to v1.x Stario.
