### ISSUE TITLE
Add Kagi as a search provider

### ISSUE THREAD

**Issue by PhilC813** [albu-razvan/Stario#67]
**Is your feature request related to a problem? Please describe.**
**[Kagi Search](https://kagi.com/)** is a first of its kind as being a paid search engine. It has a steadily increasing [user base](https://kagi.com/stats), thanks to being completely ad-free, very much user-driven thanks to a [feedback board](https://kagifeedback.org/), and being featured in the "[De-Google your life](https://youtu.be/YnSv8ylLfPw?t=307&si=6kh6PwNtzqNBdfnU)" video series of prominent Youtube channel Linus Tech Tips. They aggregate search results from multiple indexes, and have already launched audacious features like "[The Assistant](https://help.kagi.com/kagi/ai/assistant.html)", which lets you converse with some of the most popular AI models, and provide them with the ability to retrieve relevant information to queries from Kagi Search. They have recently launched an [Android app](https://play.google.com/store/apps/details?id=com.kagi.search) and are working on one for iOS.

**Describe the solution you'd like**
Add Kagi Search as a search engine. The URL scheme is indicated [here](https://help.kagi.com/kagi/getting-started/setting-default.html#custom_use). Don't hesitate to ask for my help to test an implementation since I know that asking for you to subscribe to Kagi is far fetched.

**Describe alternatives you've considered**
Through the new Kagi Android app, a search bar widget is provided, similar to the one from the Google app. However, widgets aren't available to put on the main screen of Stario yet, and it would obviously be more seamless if it was integrated as a search provider within Stario itself.

**Additional context**
![Screenshot_20241213_144229](https://github.com/user-attachments/assets/e949576f-92bb-467c-ade2-cca22704946c)

**Comment by PhilC813** [comment]
Thank you so much for adding this! If it can be relevant, I was told by Kagi's CEO over Discord that they have an API which they may provide access to if developers request access to, and that it should be made public in the future.

**Comment by albu-razvan** [comment]
Search results would be a cool addition to the launcher. Please reach out through [e-mail](mailto:razvan-albu@hotmail.com) to discuss more.
