### ISSUE TITLE
Add support for app shortcuts 

### ISSUE THREAD

**Issue by PhilC813** [albu-razvan/Stario#70]
**Is your feature request related to a problem? Please describe.**
Many developers have implemented [shortcuts](https://developer.android.com/develop/ui/views/launch/shortcuts) into their apps so as to access specific sections of their apps faster from your home screen. They're by no means essential, but after having used a few of them on my OEM's launcher (hold an app icon) and then the Niagara launcher (swipe left on an app in the list), I feel powerless without them after having moved over to Stario (slight exaggeration).

**Describe the solution you'd like**
Stario already has the "long press" action used to move apps to different categories, but I don't see any other intuitive action to implement shortcuts. I would suggest adopting a similar behaviour to most regular launchers, which is that the long press opens the menu with said shortcuts, and if the user moves his finger away from the icon while still holding it dosn, then the icon follows and you can move it to other categories. This is also the implementation made by Apple on the iOS/iPadOS home screen.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by albu-razvan** [comment]
Already exist in the [latest version](https://github.com/albu-razvan/Stario/releases/tag/v2.5).

**Comment by PhilC813** [comment]
Unless I'm missing something, it seems like the shortcuts have taken over the categories/folder capability. I would assume that it's because the launcher has been completely reworked and that it'll be added back in the future, but I'm mentioning just in case; categories in the Play Store build were quite nice.

> I would suggest adopting a similar behaviour to most regular launchers, which is that the long press opens the menu with said shortcuts, and if the user moves his finger away from the icon while still holding it dosn, then the icon follows and you can move it to other categories.

This is where this implementation would be useful to adopt.
